export const PLATFORMS = ["YouTube", "X", "TikTok", "Instagram", "Substack", "Discord", "Reddit", "StockTwits"] as const;
export const KINDS = ["creator", "community", "newsletter", "sponsor"] as const;
export const GROUP_NAMES = { creator: "Creators", newsletter: "Newsletters", community: "Communities", sponsor: "Potential sponsors" } as const;
export const CONTACT_TYPES = ["email", "form", "substack", "modmail", "discord-mod"] as const;
export const NICHES = ["earnings", "options", "day trading", "swing", "general investing"] as const;
export const US_FOCUS = ["yes", "mixed", "unknown"] as const;
export const STAGES = ["New", "Contacted", "Replied", "Joined", "Declined"] as const;
export const BASE_CSV_COLUMNS = ["name", "handle", "platform", "kind", "audience_size", "niche", "us_focus", "contact", "tracked_slug", "stage", "signups", "last_touch", "notes"] as const;
export const LEGACY_AUDIT_COLUMNS = ["source_url_live", "contact_source_url", "us_trader_fit", "fit_evidence", "verified_at"] as const;
export const AUDIT_COLUMNS = [...LEGACY_AUDIT_COLUMNS, "contact_type", "contact_evidence_file", "covers_earnings", "earnings_evidence", "earnings_source_url", "promotion_rules", "audience_evidence", "source_url", "priority_score", "earnings_evidence_file"] as const;
export const CSV_COLUMNS = [...BASE_CSV_COLUMNS, ...AUDIT_COLUMNS] as const;
export type Stage = typeof STAGES[number];
export interface Lead {
  name: string;
  handle: string;
  platform: typeof PLATFORMS[number];
  kind: typeof KINDS[number];
  audience_size: number;
  niche: typeof NICHES[number];
  us_focus: typeof US_FOCUS[number];
  contact: string;
  tracked_slug: string;
  stage: Stage;
  signups: number;
  last_touch: string;
  notes: string;
  source_url_live?: "y" | "n";
  contact_source_url?: string;
  us_trader_fit?: "strong" | "partial" | "weak";
  fit_evidence?: string;
  verified_at?: string;
  contact_type?: typeof CONTACT_TYPES[number];
  contact_evidence_file?: string;
  covers_earnings?: "y" | "n";
  earnings_evidence?: string;
  earnings_source_url?: string;
  earnings_evidence_file?: string;
  promotion_rules?: string;
  audience_evidence?: string;
  source_url?: string;
  priority_score?: number;
}
export type Weights = { audience: number; niche: number; us_focus: number; contact: number };
