import type { Metadata, Viewport } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// iOS launch images: one per device size, light and dark. Generated by scripts/design/make-icons.mjs.
const SPLASH: [number, number, number][] = [[375, 667, 2], [390, 844, 3], [393, 852, 3], [414, 896, 2], [414, 896, 3], [430, 932, 3], [820, 1180, 2], [834, 1194, 2], [1024, 1366, 2]];
const startupImage = SPLASH.flatMap(([w, h, r]) => (["light", "dark"] as const).map(scheme => ({
  url: `/splash/${scheme}-${w}x${h}@${r}x.png`,
  media: `(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${r}) and (orientation: portrait) and (prefers-color-scheme: ${scheme})`,
})));

export const metadata: Metadata = {
  metadataBase: new URL("https://gg-tourney-hub.vercel.app"),
  alternates: { canonical: "https://gg-tourney-hub.vercel.app" },
  title: "GG Outreach",
  description: "Private workspace for the GG team only",
  robots: { index: false, follow: false },
  applicationName: "GG Outreach",
  appleWebApp: { capable: true, title: "GG Outreach", statusBarStyle: "default", startupImage },
  formatDetection: { telephone: false },
  icons: { icon: [{ url: "/icon.svg", type: "image/svg+xml" }, { url: "/favicon.ico" }], apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }] },
  openGraph: { title: "GG Outreach", description: "Private workspace for the GG team only", type: "website" },
  twitter: { card: "summary_large_image", title: "GG Outreach", description: "Private workspace for the GG team only", images: ["/opengraph-image.png"] },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  colorScheme: "light dark",
  themeColor: [{ media: "(prefers-color-scheme: light)", color: "#f6f7f9" }, { media: "(prefers-color-scheme: dark)", color: "#0a0d12" }],
};

// Applies a stored appearance before first paint (no flash). Runs with the request's CSP nonce.
const THEME_INIT = `try{var t=localStorage.getItem("gg-theme");t=t&&JSON.parse(t);if(t==="light"||t==="dark")document.documentElement.setAttribute("data-theme",t)}catch(e){}`;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Request-time rendering lets Next attach this response's CSP nonce to scripts.
  const nonce = (await headers()).get("x-nonce") ?? undefined;
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full">
        <Script id="gg-theme-init" strategy="beforeInteractive" nonce={nonce}>{THEME_INIT}</Script>
        {children}
      </body>
    </html>
  );
}
