"use client";
import { useEffect } from "react";
import { useEmail } from "@/contexts/EmailContext";
import { sendingState } from "@/lib/email-state";
import { RelTime } from "@/components/ui/RelTime";
import { Skeleton } from "@/components/ui/Skeleton";
const value = (n: number | null | undefined) => n == null ? "Awaiting metrics" : n.toLocaleString();
function rate(n: number | null, denominator: number | null) { return n === null || !denominator ? "—" : `${(100 * n / denominator).toFixed(1)}%`; }
function change(current: number | null, previous: number | null) { return current === null || previous === null ? "—" : `${current - previous > 0 ? "+" : ""}${(current - previous).toLocaleString()}`; }
function EmailSkeleton() {
  return <div aria-hidden="true" className="gg-email-skeleton"><section className="gg-lead-panel"><div className="gg-list-heading"><Skeleton className="gg-sk-name" /></div><div className="gg-skel-table">{Array.from({ length: 8 }, (_, i) => <div key={i} className="gg-skel-row"><Skeleton className="gg-sk-name" /><Skeleton className="gg-sk-chip" /><Skeleton className="gg-sk-chip gg-sk-hide-sm" /></div>)}</div></section></div>;
}
export function EmailView() {
  const { data, busy, error, refresh } = useEmail();
  // Opening the view always asks for fresh numbers; the provider shares an in-flight read.
  useEffect(() => { const t = setTimeout(() => void refresh(), 0); return () => clearTimeout(t); }, [refresh]);
  const live = data?.live;
  const campaign = live?.campaign;
  const history = data?.history ?? [];
  const recordedBatches = history.filter(s => s.metrics.campaign?.id === campaign?.id).flatMap(s => s.metrics.batches);
  const byDay = new Map([...recordedBatches.reverse(), ...(live?.batches ?? [])].map(b => [b.date,b]));
  const batches = [...byDay.values()].sort((a,b) => b.date.localeCompare(a.date));
  const last = batches[0]; const previous = batches[1];
  return <div className="gg-workspace"><main id="main" tabIndex={-1} aria-labelledby="page-title"><div className="gg-workspace-header"><div className="gg-container gg-header-content"><div><p className="gg-eyebrow">Instantly · Read-only</p><h1 id="page-title">Email</h1><p>Sending inboxes, tournament campaign and daily trends.</p></div><button className="gg-button" disabled={busy} onClick={() => void refresh()}>{busy ? "Loading…" : "Refresh live data"}</button></div></div><div className="gg-container gg-email-main">
    <p className="gg-storage-note">Today and send-day batches use UTC. This view cannot send emails or change Instantly settings.</p>
    {(error || data?.error) && <p role="alert" className="gg-error">{error || data?.error}</p>}
    <p className="gg-load-status gg-sr-only" role="status">{busy ? "Reading live Instantly metrics…" : ""}</p>
    <div className="gg-email-live" aria-busy={busy}>{!live && busy && !data && <EmailSkeleton />}{live && <><p className="gg-storage-note">Live data fetched <RelTime value={live.fetchedAt} />.</p><section className="gg-lead-panel"><div className="gg-list-heading"><h2>Sending inboxes</h2><span>{live.day} UTC</span></div>{!live.inboxes.length ? <div className="gg-empty"><h3>No sending inboxes connected</h3><p>Connect your sending accounts in Instantly, then refresh.</p></div> : <div className="gg-table-scroll" role="region" aria-label="Sending inbox metrics" tabIndex={0}><table className="gg-table"><thead><tr>{["Inbox", "Warmup status", "Health score", "Sent today", "Daily limit"].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{live.inboxes.map(i => <tr key={i.email}><td>{i.email}</td><td>{i.warmup === "Unavailable" ? "Awaiting warmup status" : i.warmup}</td><td>{value(i.health)}{i.health !== null && " / 100"}</td><td>{i.sentToday == null ? sendingState(live) : value(i.sentToday)}</td><td>{value(i.dailyLimit)}</td></tr>)}</tbody></table></div>}<p className="gg-email-note">Health is Instantly’s warmup score. Sent today counts campaign emails; pending counts show the campaign state.</p></section>
    <section className="gg-lead-panel"><div className="gg-list-heading"><h2>{campaign ? campaign.name : "Tournament campaign"}</h2></div>{!campaign ? <div className="gg-empty"><h3>{live.campaignMessage}</h3><p>Your inboxes are warming up. Campaign results and send comparisons will appear after launch.</p></div> : <><div className="gg-email-metrics">{([{ label: "Sent", count: campaign.sent, percentage: "Email volume" }, { label: "Opened", count: campaign.opened, percentage: rate(campaign.opened, campaign.contacted) }, { label: "Replied", count: campaign.replied, percentage: rate(campaign.replied, campaign.contacted) }, { label: "Bounced", count: campaign.bounced, percentage: rate(campaign.bounced, campaign.contacted) }, { label: "Unsubscribed", count: campaign.unsubscribed, percentage: rate(campaign.unsubscribed, campaign.contacted) }]).map(m => <div key={m.label}><h3>{m.label}</h3><strong>{value(m.count)}</strong><small>{m.percentage}</small></div>)}</div><p className="gg-email-note">Lifetime campaign totals. Rates divide unique leads by {value(campaign.contacted)} contacted leads. Replies exclude automatic replies. “—” means the denominator or metric has not been reported.</p></>}</section>
    {campaign && <section className="gg-lead-panel"><div className="gg-list-heading"><h2>Send batch comparison</h2><span>UTC send days</span></div>{!last ? <div className="gg-empty"><h3>No send batches recorded yet</h3><p>After launch, each day with sends is compared with the previous sending day.</p></div> : <><p className="gg-email-note">Latest {last.date}{previous ? ` vs ${previous.date}: sent ${change(last.sent, previous.sent)}, opened ${change(last.opened, previous.opened)}, replied ${change(last.replied, previous.replied)}.` : ": waiting for a previous send day to compare."} Opens and replies are observed on that day, not attributed to that day’s recipients. These are operational daily batches.</p><div className="gg-table-scroll" role="region" aria-label="Send batch comparison" tabIndex={0}><table className="gg-table"><thead><tr>{["Send day", "Sent", "Δ vs previous", "Contacted", "Unique opens", "Unique replies", "Replies / contacted"].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{batches.map((b,i) => <tr key={b.date}><td>{b.date}</td><td>{value(b.sent)}</td><td>{batches[i+1] ? change(b.sent, batches[i+1].sent) : "—"}</td><td>{value(b.contacted)}</td><td>{value(b.opened)}</td><td>{value(b.replied)}</td><td>{rate(b.replied,b.contacted)}</td></tr>)}</tbody></table></div></>}</section>}</>}</div>
    <section className="gg-lead-panel"><div className="gg-list-heading"><h2>Daily snapshot trends</h2><span>00:05 UTC · up to 90 days</span></div>{data?.historyError && <p role="alert" className="gg-error">{data.historyError}</p>}{!history.length ? <div className="gg-empty"><h3>No daily snapshots yet</h3><p>The daily job records real inbox and campaign metrics after Instantly is connected. Failed reads do not create a snapshot.</p></div> : <>{history.some(s => s.metrics.campaign) && <div className="gg-table-scroll" role="region" aria-label="Campaign snapshot trends" tabIndex={0}><table className="gg-table"><thead><tr>{["Snapshot day", "Campaign", "Sent total", "Opened", "Replied", "Bounced", "Unsubscribed"].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{history.filter(s => s.metrics.campaign).map(s => <tr key={s.day}><td>{s.day}</td><td>{s.metrics.campaign?.name ?? s.metrics.campaignMessage}</td><td>{value(s.metrics.campaign?.sent)}</td><td>{value(s.metrics.campaign?.opened)}</td><td>{value(s.metrics.campaign?.replied)}</td><td>{value(s.metrics.campaign?.bounced)}</td><td>{value(s.metrics.campaign?.unsubscribed)}</td></tr>)}</tbody></table></div>}<div className="gg-table-scroll" role="region" aria-label="Inbox snapshot trends" tabIndex={0}><table className="gg-table"><thead><tr>{["Snapshot day", "Inbox", "Warmup", "Health", "Sent at capture", "Daily limit"].map(h => <th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{history.flatMap(s => s.metrics.inboxes.map(i => <tr key={`${s.day}-${i.email}`}><td>{s.day}</td><td>{i.email}</td><td>{i.warmup === "Unavailable" ? "Awaiting warmup status" : i.warmup}</td><td>{value(i.health)}</td><td>{i.sentToday == null ? sendingState(s.metrics) : value(i.sentToday)}</td><td>{value(i.dailyLimit)}</td></tr>))}</tbody></table></div><p className="gg-email-note">Each snapshot is immutable for its UTC day; retries are idempotent. Inbox sent counts reflect the capture time, not a full day. Two daily snapshots are needed to compare changes.</p></>}</section>
  </div></main></div>;
}
