from pathlib import Path
import json
r=Path('.')
p=r/'src/config/fit-weights.json';c=json.loads(p.read_text());c['tiers']={'priorityMinimumReach':1000,'unknownReachValues':[0],'nonUsFitPatterns':['geography.*unconfirmed','geographic focus.*unconfirmed','US[- ](?:stock|only).*?(?:unconfirmed|not established)','without explicit US-only coverage','Indian|European index','global multi-asset.*rather than US']};p.write_text(json.dumps(c,indent=2)+'\n')
p=r/'src/lib/outreach.ts';s=p.read_text();pos=s.index('export const DEFAULT_WEIGHTS');s=s[:pos]+'''/** Reversible display tier; never persisted into workflow fields. */
export function leadTier(lead: Lead): "priority" | "long-tail" {
  return !Number.isFinite(lead.audience_size) || config.tiers.unknownReachValues.includes(lead.audience_size) || lead.audience_size < config.tiers.priorityMinimumReach || config.tiers.nonUsFitPatterns.some(pattern => new RegExp(pattern, "i").test(lead.fit_evidence ?? "")) ? "long-tail" : "priority";
}

'''+s[pos:];p.write_text(s)
p=r/'src/components/outreach/Workspace.tsx';s=p.read_text().replace('isExample, leadGroup','isExample, leadGroup, leadTier');s=s.replace('  const visible = leads.filter', '  const [showLongTail, setShowLongTail] = useState(false);\n  const tierLeads = leads.filter(l => showLongTail || leadTier(l) === "priority");\n  const longTailCount = leads.filter(l => !isExample(l) && leadTier(l) === "long-tail").length;\n  const visible = tierLeads.filter');s=s.replace('const real = leads.filter', 'const real = tierLeads.filter');s=s.replace('{!pipeline && <StatusStrip />}', '<StatusStrip />');s=s.replace('<div className="gg-filters"><div', '<div className="gg-filters"><label className="gg-toggle"><input type="checkbox" checked={showLongTail} onChange={e => setShowLongTail(e.target.checked)} />Show long tail ({longTailCount})</label><div');s=s.replace('setSort("fit"); }}','setSort("fit"); setShowLongTail(false); }}');s=s.replace('<ClickAnalytics /><ConversionLoop />','<ClickAnalytics scopedLeads={real} /><ConversionLoop scopedLeads={real} />');p.write_text(s)
p=r/'src/components/outreach/StatusStrip.tsx';s=p.read_text().replace('isExample, leadGroup','isExample, leadGroup, leadTier');s=s.replace('  const groups =', '  const priorityCount = real.filter(l => leadTier(l) === "priority").length;\n  const longTailCount = real.length - priorityCount;\n  const groups =');s=s.replace('All qualified groups · ${groups.join', 'Priority: ${priorityCount} · Long tail: ${longTailCount} · ${groups.join');p.write_text(s)
p=r/'src/components/outreach/ConversionLoop.tsx';s=p.read_text().replace('isExample, leadGroup','isExample, leadGroup, suggestedWeights');s=s.replace('export function ConversionLoop() {','export function ConversionLoop({ scopedLeads }: { scopedLeads: Lead[] }) {');s=s.replace('const { leads, clicks, suggestion, useSuggested, setUseSuggested } = useOutreach();','const { clicks, useSuggested, setUseSuggested } = useOutreach();\n  const leads = scopedLeads;\n  const suggestion = suggestedWeights(leads);');s=s.replace('All imported leads, excluding EXAMPLE rows.', 'Visible tier leads, excluding EXAMPLE rows.');p.write_text(s)
p=r/'src/lib/server/clicks.ts';s=p.read_text().replace('[leads, groups, daily, tests]', '[leads, groups, daily, tests, dailyBySlug]');s=s.replace('  ]);\n  return { leads, groups, daily, tests };', '''    sql`SELECT slug, to_char(clicked_at AT TIME ZONE 'UTC', 'YYYY-MM-DD') AS day, count(*)::int AS clicks FROM gg_clicks WHERE NOT is_test AND NOT is_example AND (clicked_at AT TIME ZONE 'UTC')::date >= (now() AT TIME ZONE 'UTC')::date - 29 GROUP BY slug, day ORDER BY day, slug`,
  ]);
  return { leads, groups, daily, tests, dailyBySlug };''');p.write_text(s)
p=r/'src/contexts/OutreachContext.tsx';s=p.read_text().replace('daily: { day:', 'dailyBySlug: { slug: string; day: string; clicks: number }[]; daily: { day:');p.write_text(s)
p=r/'src/components/outreach/ClickAnalytics.tsx';s=p.read_text().replace('import { useState }','import type { Lead } from "@/types/outreach";\nimport { useState }');s=s.replace('export function ClickAnalytics() {\n  const { clicks, leads } = useOutreach();', '''export function ClickAnalytics({ scopedLeads: leads }: { scopedLeads: Lead[] }) {
  const { clicks } = useOutreach();
  const slugs = new Set(leads.map(l => l.tracked_slug));
  const daily = clicks?.daily.map(d => ({ day: d.day, clicks: (clicks.dailyBySlug ?? []).filter(row => row.day === d.day && slugs.has(row.slug)).reduce((n, row) => n + row.clicks, 0) }));''');s=s.replace('    const group = lead ? leadGroup(lead) : "Archived outreach";', '    if (!lead) continue;\n    const group = leadGroup(lead);');s=s.replace('clicks?.daily','daily').replace('const daily = daily.map', 'const daily = clicks?.daily.map').replace('clicks.daily.map','daily?.map').replace('clicks?.groups.reduce((n, g) => n + g.clicks, 0)', 'groupRows.reduce((n, g) => n + g.clicks, 0)').replace('clicks.daily[0]', 'daily?.[0]').replace('clicks.daily.at(-1)', 'daily?.at(-1)');p.write_text(s)
