import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {chromium,expect} from '@playwright/test';
const origin='https://gg-tourney-hub.vercel.app',root='evidence/preclient';const cookie=await fs.readFile(root+'/.session','utf8');const [name,...parts]=cookie.split('=');const results=[];await fs.mkdir(root+'/screenshots',{recursive:true});
const raw=await(await fetch(origin+'/api/leads',{headers:{Cookie:cookie}})).json();const lead=raw.leads.find(l=>l.tracked_slug==='audit-claytrader');
for(const channel of ['chrome','msedge']){let browser;try{browser=await chromium.launch({channel});}catch(e){results.push({channel,status:'FAIL',error:e.message});continue;}
for(const width of [390,820,1440])for(const motion of ['normal','reduce']){const c=await browser.newContext({viewport:{width,height:960},reducedMotion:motion==='reduce'?'reduce':'no-preference'});let p=await c.newPage();const errors=[];let expectedFault=false;p.on('pageerror',e=>errors.push({type:'runtime',message:e.message}));p.on('console',m=>{if(m.type()==='error'&&!expectedFault)errors.push({type:'console',message:m.text()});});
const run={channel,version:browser.version(),width,motion,views:[],errors,status:'PASS'};const prefix=`${channel}-${width}-${motion}`;
async function shot(view){await p.evaluate(()=>document.fonts.ready);const file=`screenshots/${prefix}-${view}.png`;await p.screenshot({path:root+'/'+file,fullPage:!await p.getByRole('dialog').count(),animations:'disabled'});const check=await p.evaluate(()=>{const faults=[];if(document.documentElement.scrollWidth>innerWidth+1)faults.push('document horizontal overflow');for(const e of document.querySelectorAll('nav a,nav button,.gg-header-content button,[role=dialog]')){const r=e.getBoundingClientRect();if(r.width&& (r.left< -1||r.right>innerWidth+1))faults.push('control/dialog clipped: '+e.textContent.slice(0,60));}if(matchMedia('(prefers-reduced-motion: reduce)').matches)for(const e of document.querySelectorAll('body *')){const s=getComputedStyle(e);if(s.animationName!=='none'||s.transitionDuration.split(',').some(v=>parseFloat(v)>0))faults.push('motion not reduced');}return [...new Set(faults)];});const copy=await p.locator('body').innerText();const hits=copy.match(/\bTODO\b|lorem|\btest\b|\bplaceholder\b|WhoRaised/gi)||[];run.views.push({view,file,url:p.url(),overflow:check,copyHits:hits,bodyText:copy});if(check.length||hits.length)run.status='FAIL';}
try{await p.goto(origin+'/login');await expect(p.locator('.gg-login-subtitle')).toHaveText('Private workspace for the GG team only');await shot('login');await c.addCookies([{name,value:parts.join('='),url:origin,httpOnly:true,secure:true,sameSite:'Strict'}]);
await p.goto(origin+'/');await expect(p.locator('.gg-name-button').first()).toBeVisible({timeout:45000});await expect(p.locator('.gg-status-strip')).not.toContainText('Loading…',{timeout:45000});await shot('home');run.statusStrip=await p.locator('.gg-status-strip').innerText();
await p.getByLabel('Show long tail').check();await shot('long-tail');await p.getByLabel('Show long tail').uncheck();await p.getByLabel('Search leads',{exact:true}).fill(lead.tracked_slug);await p.getByRole('button',{name:lead.name+' '+lead.handle,exact:true}).click();await shot('drawer');await p.locator('.gg-draft').scrollIntoViewIfNeeded();await shot('draft');await p.getByRole('button',{name:'Close dialog',exact:true}).click();await p.getByLabel('Search leads',{exact:true}).fill('');
await p.getByRole('button',{name:'Export CSV',exact:true}).click();await shot('export');const exported=await p.getByLabel('CSV preview').inputValue();await p.getByRole('button',{name:'Close dialog',exact:true}).click();await p.getByRole('button',{name:'Import CSV',exact:true}).click();await shot('import');await p.getByLabel('Or paste CSV').fill(exported);await p.getByRole('button',{name:'Validate CSV',exact:true}).click();await expect(p.getByRole('region',{name:'Import preview'})).toBeVisible();await shot('import-preview');await p.getByRole('button',{name:'Close dialog',exact:true}).click();
await p.locator('#click-title').scrollIntoViewIfNeeded();await shot('analytics');await p.getByLabel('Show QA activity').check();await shot('qa-activity');await p.getByLabel('Show QA activity').uncheck();await p.getByLabel('Search leads',{exact:true}).fill('no matching outreach record xyz');await shot('no-matches');
await p.goto(origin+'/pipeline');await expect(p.locator('.gg-pipeline-card').first()).toBeVisible({timeout:45000});await shot('pipeline');await p.goto(origin+'/email');await expect(p.getByRole('button',{name:'Refresh live data',exact:true})).toBeVisible({timeout:45000});await expect(p.getByRole('region',{name:'Sending inbox metrics'}).locator('tbody tr')).toHaveCount(8,{timeout:45000});await shot('email');run.emailRows=await p.getByRole('region',{name:'Sending inbox metrics'}).locator('tbody tr').evaluateAll(rows=>rows.map(r=>[...r.querySelectorAll('td')].map(t=>t.textContent)));
expectedFault=true;await p.goto(origin+'/not-a-real-page');await expect(p.getByRole('heading',{name:'Page not found'})).toBeVisible();await shot('404');expectedFault=false;
// Read-only fault injection exercises presentation, without altering production data.
for(const view of ['home','pipeline','email'])for(const state of ['loading','empty','error']){await p.close();p=await c.newPage();p.on('pageerror',e=>errors.push({type:'runtime',message:e.message}));const api=view==='email'?'/api/email':'/api/leads';expectedFault=state==='error';await p.route('**'+api,async route=>{if(state==='loading')await new Promise(r=>setTimeout(r,3500));if(state==='empty')await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(view==='email'?{live:{fetchedAt:new Date().toISOString(),day:'2026-10-07',inboxes:[],campaign:null,campaignMessage:'No campaign yet',batches:[]},history:[],error:'',historyError:''}:{leads:[],clicks:{leads:[],groups:[],daily:[],dailyBySlug:[],tests:[]}})});else if(state==='error')await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Shared workspace could not be loaded. Retry shortly.'})});else await route.continue();});await p.goto(origin+(view==='home'?'/':'/'+view));if(state==='loading')await expect(p.getByRole('status').filter({hasText:view==='email'?'Reading live Instantly metrics':'Loading shared workspace'}).first()).toBeVisible();else if(state==='error')await expect(p.getByRole('alert').first()).toBeVisible();else await expect(p.getByRole('heading',{name:view==='email'?'No sending inboxes connected':'Build your outreach list'})).toBeVisible();await shot(view+'-'+state);await p.unrouteAll({behavior:'wait'});expectedFault=false;}
if(errors.length)run.status='FAIL';
}catch(e){run.status='FAIL';run.failure=e.message;await p.screenshot({path:root+`/screenshots/${prefix}-failure.png`,fullPage:true}).catch(()=>{});}finally{results.push(run);await fs.writeFile(root+'/viewports.json',JSON.stringify(results,null,2));await c.close();console.log(prefix,run.status,run.views.length,run.failure?.slice(0,100)||'');}}
await browser.close();}console.log('done',results.length);




