from pathlib import Path
import json, collections
root=Path.cwd();read=lambda path:json.loads((root/path).read_text(encoding='utf-8'))
audit=read('data/creator-demo-audit.json');verification=read('evidence/demo-readiness/verification.json');state=read('evidence/demo-readiness/final-state-proof.json');clicks=read('evidence/demo-readiness/live-click-classification.json')
esc=lambda value:str(value).replace('|','\\|').replace('\n',' ')
accepted=audit['accepted'];by_slug={l['tracked_slug']:l for l in accepted}
top=['audit-humbledtrader','audit-optionalpha','r1-bthetrader87','r1-traderisk','r1-fxevolutionvideo','r1-optionstrat','r1-trendspider','r1-stockstotrade','r1-optionswithdavis','r1-projectoption','audit-smbcapital','audit-claytrader','r1-alphatrends','r1-benzinga','audit-schaeffersresearch']
groups=collections.Counter(l['platform'] for l in accepted);ratings=collections.Counter(l['us_trader_fit'] for l in accepted)
report=['# Creator list audit — 7 October 2026','',f"Independent original audit: **{audit['before']} real rows → {audit['retained']} retained, {audit['removed']} removed. {audit['backfilled']} replacements → {audit['after']} qualified rows.** The EXAMPLE QA fixture is separate.",'',
'Every original source URL was requested afresh. YouTube channel metadata/video titles, Substack About text and the public X feed were parsed from the loaded page. Discord names/member counts were additionally checked through its public invite API. Reddit returned generic application shells; those rows were removed because current content/fit and a business route were not verified. A 200 response alone did not establish qualification.',
'', 'Contacts were checked on public creator/company pages, About descriptions, sponsorship pages or general company inquiry forms. A company form counts only where it invites public company/general inquiries, commercial collaborations or partnerships. Customer-account-only support and generic social DMs were insufficient. Personal-looking addresses were rejected even on corporate domains. No emails or forms were submitted.',
'','The fit rating describes coverage of US stocks/options and the relevance of the trading audience. It does not establish US audience residency. Partial rows cover global markets, investing, futures or professional audiences. Newsletter sizes not published on the freshly loaded page are **unknown**, represented by `0` in the existing numeric CSV schema. Subscriber counts are approximate public rounded displays; Discord member counts are live approximate invite counts.',
'', 'The 50 rows represent **46 owners**, rather than 50 independent owners: TanukiTrade and Unusual Whales each have two surfaces; the Dow Jones contact serves WSJ, Barron’s and MarketWatch. Coordinate outreach to each owner. No count was padded with identical channels.',
'',f"Final groups: {', '.join(f'{k}: {v}' for k,v in sorted(groups.items()))}. Fit: {', '.join(f'{k}: {v}' for k,v in sorted(ratings.items()))}.",
'','## Top 15 for review','','Editorial priority favors specific business/sponsorship routes and direct trading relevance. This selection is independent of the application’s configured score; no pipeline ranking UX was changed.','','| Name | Platform | Audience size | Fit evidence | contact_source_url |','|---|---|---:|---|---|']
for slug in top:
 l=by_slug[slug];report.append('| '+ ' | '.join([esc(l['name']),l['platform'],f"{l['audience_size']:,}" if l['audience_size'] else 'unknown',esc(l['us_trader_fit']+': '+l['fit_evidence']),l['contact_source_url']])+' |')
report+=['','## Original removals','','| Name | Platform | Fit | Reason |','|---|---|---|---|']
for r in audit['records']:
 if r['decision']=='remove':
  l=r['lead'];report.append('| '+ ' | '.join(map(esc,[l['name'],l['platform'],l['us_trader_fit'],r['reason']]))+' |')
report+=['','## Replacements','','| Name | Fit | Public business source |','|---|---|---|']
for r in audit['records']:
 if r['decision']=='backfill':
  l=r['lead'];report.append(f"| {esc(l['name'])} | {l['us_trader_fit']} | {l['contact_source_url']} |")
report+=['','Two provisional replacements were rejected during the final contact review: Zacks (only a personal-looking ad-sales address verified) and Investor’s Business Daily (advertising page contact form did not render). They were archived after the first reconciliation. StockCharts’ verified advertising route restored one original row; Seeking Alpha’s public commercial partnership form replaced the other.',
'','Some contact pages blocked the direct HTTP crawler. Benzinga’s advertising page loaded in real Chrome and published `partnerships@benzinga.com`; Dow Jones’ events contact also loaded in Chrome. Morningstar’s role contact and TraderLion’s public company form were read through the web page reader; Chrome access respectively returned 202/Cloudflare. These transport limitations are preserved in the source evidence rather than described as Chrome passes.',
'','## Files and live reconciliation','',
'- [All 66 original rows with audit columns](../data/creator-list-r1-audited-all.csv).',
'- [Final 50-row audited CSV](../data/creator-list-audited.csv).',
'- [Per-row decisions, evidence and checked times](../data/creator-demo-audit.json).',
'- [Fresh original source loads](../data/creator-audit-source-loads.json), [contact loads](../data/creator-contact-loads.json), [follow-up loads](../data/creator-corrected-loads.json), [final business routes](../data/creator-last-loads.json).',
'- Source HTML is retained in [creator-audit evidence](../evidence/creator-audit/).',
'- [Original-to-final pipeline preservation proof](../evidence/demo-readiness/final-state-proof.json).',
'', 'The production import merged only research/contact fields. Existing stage, signups, last_touch and notes were preserved against the original 67-row database snapshot, including the fixture. Original removals and superseded provisional records are recoverable in `gg_creator_audit_archive` under run ID `demo-creator-audit-2026-10-07`. Historical R1 notes remain preserved; the new audit columns and this report are the current research evidence. The original R1 CSV is retained as the input baseline.']
(root/'docs/CREATOR_LIST_AUDIT.md').write_text('\n'.join(report)+'\n',encoding='utf-8')

all_pass=len(verification['checks'])==12 and all(r['status']=='PASS' for r in verification['checks'])
demo=['# Demo readiness — 7 October 2026','', '**READY**' if all_pass else '**NOT READY**','',
'Canonical viewer URL: **https://gg-tourney-hub.vercel.app**. `gg-outreach.vercel.app` was occupied; the next requested alias succeeded. Vercel’s CLI was authenticated. The alias was additionally registered as a verified production project domain so fresh viewers receive the dashboard login rather than Vercel SSO. Project/deployment names remain internal.',
'','Old-host dashboard/login/pipeline/email paths redirect to the canonical host. Old-host `/go/` requests retain the existing redirect behavior. Pitch text, clickable pitch links and canonical metadata use the clean host. Login wording and pipeline UX were preserved.',
'','## Viewer matrix','',
'Installed real Chrome and Edge ran headed, with a fresh incognito browser context for each viewport/motion combination. No stored login session or spoofed user agent was used. Dimensions are CSS viewport widths, height 960. Reduced-motion checks additionally verified no active CSS animation/transition. Screenshots show page content; browser navigation URLs were recorded separately in the verification JSON to verify the address-bar destination. Native browser chrome is not included in page screenshots.',
'','The overflow gate follows your clarification: **no page-level horizontal overflow; existing internal pipeline/table scrolling is allowed**. Each row checks login, fully loaded home/status strip, pitch, analytics and fully loaded pipeline. Login HTML was checked for audited creator names and tracked slugs; unauthenticated leads requests return 401.',
'','| Browser | Width | Motion | Clean host/text | No pre-auth names | No page overflow | Strip readable | No console errors | Test counts excluded | Captures |','|---|---:|---|---|---|---|---|---|---|---|']
for r in verification['checks']:
 prefix=f"{r['channel']}-{r['width']}-{'reduce' if r['reducedMotion']=='reduce' else 'normal'}"
 paths=['login','home','pipeline','pitch','analytics'];links=' · '.join(f'[{view}](../evidence/demo-readiness/{prefix}-{view}.png)' for view in paths)
 status=r['status'];demo.append(f"| {'Chrome' if r['channel']=='chrome' else 'Edge'} {r['version']} | {r['width']} | {'Reduced' if r['reducedMotion']=='reduce' else 'Normal'} | {status} | {status} | {status} | {status} | {status} | {status} | {links} |")
demo+=['','[Machine verification, actual URLs, dimensions, metrics and browser versions](../evidence/demo-readiness/verification.json). Full home/pipeline page captures accompany each viewport capture in the same directory. Earlier SSO failures are retained in [alias-sso-failure.json](../evidence/demo-readiness/alias-sso-failure.json); they are superseded by the production-domain registration and final matrix.',
'','## Real click and permanent test hygiene','',f"The natural Chrome 390 click on `{verification['clickProof']['slug']}` moved its real count from {verification['clickProof']['before']} to {verification['clickProof']['after']}, once. Landing: {verification['clickProof']['landing']}. [Landing capture](../evidence/demo-readiness/real-click-landing-390.png). The proof was retained rather than generating another real click during capture reruns.",
'','Twitter, Facebook, Slack, Discord, LinkedIn, WhatsApp and Telegram previews, a prefetch request, and HEAD checks did not move the real count. Canonical and old-host HEAD redirects returned the same creator UTM attribution. A normal request with `?test=1` created a test event while per-lead, group and daily real arrays stayed unchanged.',
'',f"Live classification: **{clicks['metrics']['real']} real click, {clicks['metrics']['tests']} test clicks**. No existing EXAMPLE/prefixed test event lacks `is_test=true`. Prefixes `example-` / `test-` and query `test=1` are classified on every new stored click. The small Show test clicks toggle is off by default; tests appear only in its separate list. Real analytics SQL filters tests before aggregating. Conversion groups and suggested weights exclude fixture/test leads. Historical click rows never stored query strings, so historical backfill uses their stored slug/EXAMPLE marker; query classification applies prospectively. The only current unmarked real event is the recorded natural mobile click.",
'','[Live click classification](../evidence/demo-readiness/live-click-classification.json), [isolated SQL aggregation proof](../evidence/demo-readiness/test-metric-proof.json), [unit coverage](../tests/click-tracking.spec.ts). Five unit/contract tests passed. Build and production deployment passed; lint has no errors (one pre-existing unused-variable warning in the R1 YouTube-date script).',
'', '[Live exported CSV](../evidence/demo-readiness/live-export.csv), [export/toggle proof](../evidence/demo-readiness/export-toggle-proof.json), [test toggle capture](../evidence/demo-readiness/chrome-390-test-toggle.png), [email view capture](../evidence/demo-readiness/chrome-390-email.png), [built/public content scan](../evidence/demo-readiness/built-content-scan.json).', '', 'Final deployed production build: `dpl_5xEgUhaRZKGz6HFboGJmZKX3Yhub`. [Canonical/old-host redirect and pre-auth proof](../evidence/demo-readiness/final-host-proof.json).', '', '## Real status and audit','',f"Instantly: **{state['status']['warming']} inboxes warming, {state['status']['averageHealth']}% average health**, {state['status']['healthMeasured']}/{state['status']['warming']} measured, snapshot timestamp {state['status']['fetchedAt']}. No campaign exists: **Waiting for prereg link**. The strip reads live data, falls back to a timestamped saved snapshot, and shows unavailable/loading states without invented numbers. A real campaign, including an unsent draft, displays its API status.",
'',f"Queued: **50 real rows** — {', '.join(f'{k}: {v}' for k,v in sorted(groups.items()))}. The separate EXAMPLE fixture explains the existing Total leads card showing 51. It is excluded from queued, signup/conversion, learning and click metrics.",
'',f"Creator audit: **66 original → {audit['retained']} retained / {audit['removed']} removed + {audit['backfilled']} replacements = 50**. [Top 15 and removal reasons](CREATOR_LIST_AUDIT.md). [Final audited CSV](../data/creator-list-audited.csv). Original pipeline fields passed exact preservation checks for retained and archived rows. [State proof](../evidence/demo-readiness/final-state-proof.json).", 
'','The source/public-file and live data scans found no user-visible old product name. The sole source occurrence is the internal old-host comparison needed for migration redirects. Favicon inspection found a symbol with no product wording; manifest/title/social metadata are GG Outreach. Email snapshot data and exported lead data were scanned too. Reports, captures and verification scripts are excluded from the Vercel upload.',
'','Remaining intentional campaign state: no prereg campaign has been created or launched. This is displayed honestly and is not a demo gate failure. The real link currently lands on the configured tournament homepage with attribution; it does not claim prereg signup completion.']
(root/'docs/DEMO_READINESS.md').write_text('\n'.join(demo)+'\n',encoding='utf-8')
lessons=root/'docs/LESSONS.md'
with lessons.open('a',encoding='utf-8') as f:
 f.write('''\n## 7 October 2026 — GG outreach demo pass\n\n- Register a clean Vercel alias as a production project domain. A manual deployment alias initially inherited Vercel SSO; check with a fresh unauthenticated session before sharing.\n- Begin each creator list with source_url_live, contact_source_url, us_trader_fit, fit_evidence and verified_at. Load every primary page afresh. A 200 application shell or a generic social DM does not prove fit or a business contact.\n- Verify official channel links. Guessed handles resolved to unrelated channels for several replacement candidates. Use a confirmed channel ID or official linked handle.\n- Reject personal-looking email addresses and customer-only support routes. Prefer explicit sponsorship/partnership addresses and published company inquiry forms. Verify that an advertised form actually renders.\n- Record unknown audience size when the checked source publishes none. Do not carry forward unsupported newsletter counts. Disclose shared owners across platform rows and coordinate outreach once per owner.\n- Store example-/test- slug clicks and ?test=1 requests as is_test at insertion. Backfill identifiable legacy fixtures, filter before every aggregation, and keep tests behind a separate toggle. Protect real group conversions and suggested weights from fixture leads.\n- Merge audit research into current records atomically, preserving stage, signups, last_touch and notes. Archive removals; verify against the original snapshot, not merely the last import.\n- Capture after shared leads finish loading. The first pipeline screenshots caught only the loading state; corrected waits now prove the populated board. Test each browser, viewport and reduced-motion combination separately.\n- Read the status strip from timestamped Instantly/workspace data. Do not hide existing unsent drafts, invent campaign status labels, or supply placeholder warmup/queue/click numbers.\n- One natural mobile click is enough for the real redirect proof. Retain that evidence across screenshot reruns so QA does not generate additional real clicks.\n''')
print(f'Wrote audit, Top 15, readiness ({"READY" if all_pass else "NOT READY"}) and lessons.')
